# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='location',
            field=models.CharField(default='my location default', max_length=40),
        ),
    ]
