# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_package_specialoffers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('depature', models.DateField(auto_now_add=True)),
                ('price1', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('price3', models.IntegerField()),
                ('price4', models.IntegerField()),
                ('price5', models.IntegerField()),
                ('price6', models.IntegerField()),
                ('price7', models.IntegerField()),
                ('itinerary', models.TextField()),
                ('bookbefore', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
    ]
