# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_excursion_briefdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='briefdetails',
            field=models.TextField(default='my details'),
        ),
    ]
