# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20181019_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoSSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('depature', models.DateField(auto_now_add=True)),
                ('price1', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('price3', models.IntegerField()),
                ('price4', models.IntegerField()),
                ('price5', models.IntegerField()),
                ('price6', models.IntegerField()),
                ('price7', models.IntegerField()),
                ('image1', models.IntegerField()),
                ('image2', models.IntegerField()),
                ('image3', models.IntegerField()),
                ('image4', models.IntegerField()),
                ('image5', models.IntegerField()),
                ('image6', models.IntegerField()),
                ('image7', models.IntegerField()),
                ('itinerary1', models.TextField()),
                ('itinerary2', models.TextField()),
                ('bookbefore', models.DateField(auto_now_add=True)),
                ('briefdetails', models.TextField(default='my details')),
            ],
        ),
        migrations.DeleteModel(
            name='SpecialOffers',
        ),
    ]
