# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20181021_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion',
            options={'verbose_name': 'excursions'},
        ),
    ]
