# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20181021_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('travelers_that_have_booked', models.IntegerField()),
                ('price1', models.FloatField()),
                ('price2', models.IntegerField()),
                ('price3', models.IntegerField()),
                ('price4', models.IntegerField()),
                ('price5', models.IntegerField()),
                ('price6', models.IntegerField()),
                ('price7', models.IntegerField()),
                ('image1', models.IntegerField()),
                ('image2', models.IntegerField()),
                ('image3', models.IntegerField()),
                ('image4', models.IntegerField()),
                ('image5', models.IntegerField()),
                ('image6', models.IntegerField()),
                ('image7', models.IntegerField()),
                ('itinerary', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('bookbefore', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Excursion',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='TwoSSF',
        ),
    ]
