# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20181022_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joingroup',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='image2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='image3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='image4',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='image5',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='image6',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='image7',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='price2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='price3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='price4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='price5',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='price6',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='price7',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='travelers_that_have_booked',
            field=models.FloatField(),
        ),
    ]
