# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20181023_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joingroup',
            old_name='details',
            new_name='brief_details',
        ),
        migrations.RenameField(
            model_name='joingroup',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='price4',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='price5',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='price6',
        ),
        migrations.RemoveField(
            model_name='joingroup',
            name='price7',
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='travelers_that_have_booked',
            field=models.IntegerField(),
        ),
    ]
