# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20181101_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joingroup',
            name='title',
        ),
        migrations.AddField(
            model_name='joingroup',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
