# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20181102_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='joingroup',
            name='title',
            field=models.CharField(default='title', max_length=120),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='travelers_that_have_booked',
            field=models.IntegerField(default=0),
        ),
    ]
