# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20181102_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joingroup',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
