# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20181102_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='joingroup',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
