# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_joingroup_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joingroup',
            old_name='show',
            new_name='Show',
        ),
    ]
