# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20181103_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joingroup',
            name='Show',
        ),
    ]
