# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_remove_joingroup_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joingroup',
            name='title',
        ),
    ]
