# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_remove_joingroup_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joingroup',
            name='brief_details',
        ),
    ]
