# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_remove_joingroup_brief_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joingroup',
            name='image',
        ),
    ]
