# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_joingroup_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteedSafaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookbefore', models.DateField()),
                ('peoplebooked', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='joingroup',
            name='title',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
