# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20181106_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='Enter_Safari_Package',
            field=models.CharField(choices=[('ExNk', 'Excursions-lakenakuru'), ('ExNv', 'Excursions-lakenaivasha'), ('ExNai', 'Excursions-nairobiexcursions')], default='title', max_length=20),
        ),
    ]
