# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_guaranteedsafaris_enter_safari_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guaranteedsafaris',
            old_name='bookbefore',
            new_name='book_before',
        ),
        migrations.RenameField(
            model_name='guaranteedsafaris',
            old_name='peoplebooked',
            new_name='people_booked',
        ),
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='Enter_Hotel_Star',
            field=models.CharField(choices=[('2', '2 star'), ('3', '3 star'), ('4', '4 star')], default='hotels', max_length=20),
        ),
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='Enter_Season',
            field=models.CharField(choices=[('lw', 'low'), ('hi', 'high'), ('pk', 'peak')], default='seasons', max_length=20),
        ),
        migrations.AlterField(
            model_name='guaranteedsafaris',
            name='Enter_Safari_Package',
            field=models.CharField(choices=[('ExNk', 'Excursions-lakenakuru'), ('ExNv', 'Excursions-lakenaivasha'), ('ExNai', 'Excursions-nairobiexcursions'), ('2dyab', '2 days - aberdare'), ('2dyam', '2 days - amboseli'), ('2dynk', '2 days - nakuru'), ('2dynv', '2 days - naivasha'), ('2dysw', '2 days - sweetwaters'), ('3dyam', '3 days - amboseli'), ('3dyma', '3 days - maasaimara '), ('3dynk', '3 days - nakuru'), ('3dysa', '3 days - samburu'), ('3dysw', '3 days - sweetwaters'), ('4dymank', '4 days - maranakuru'), ('5dyam', '5 days - amboseli')], default='title', max_length=20),
        ),
    ]
