# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20181106_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteedsafaris',
            name='Enter_Safari_Package',
            field=models.CharField(choices=[('ExNakuru', 'Excursions-lakenakuru'), ('ExNaivasha', 'Excursions-lakenaivasha'), ('ExNairobi', 'Excursions-nairobiexcursions'), ('2dyabedare', '2 days - aberdare'), ('2dyamboseli', '2 days - amboseli'), ('2dynakuru', '2 days - nakuru'), ('2dynaivasha', '2 days - naivasha'), ('2dysweetwaters', '2 days - sweetwaters'), ('3dyamboseli', '3 days - amboseli'), ('3dymaasaimara', '3 days - maasaimara '), ('3dynakuru', '3 days - nakuru'), ('3dysamburu', '3 days - samburu'), ('3dysweetwaters', '3 days - sweetwaters'), ('4dymaranakuru', '4 days - maranakuru'), ('5dyamboseli', '5 days - amboseli')], default='title', max_length=20),
        ),
    ]
