# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_auto_20181106_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guaranteedsafaris',
            name='Enter_Season',
        ),
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='price1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='price2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='price3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='price4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='price5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='price6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='price7',
            field=models.IntegerField(default=0),
        ),
    ]
