# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20181107_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joingroup',
            name='bookbefore',
        ),
    ]
