# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_auto_20181107_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowseason',
            name='package',
        ),
    ]
