# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_remove_lowseason_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='book_before',
            field=models.DateField(default=datetime.now()),
        ),
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='depature_date',
            field=models.DateField(default=datetime.now()),
        ),
        migrations.AddField(
            model_name='lowseason',
            name='package',
            field=models.OneToOneField( on_delete=django.db.models.deletion.CASCADE, to='profiles.Packages'),
        ),
    ]
