# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_auto_20181107_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteedsafaris',
            name='book_before',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guaranteedsafaris',
            name='depature_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
