# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0046_auto_20181107_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteedsafaris',
            name='book_before',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guaranteedsafaris',
            name='depature_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
