# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import datetime as date
from datetime import datetime; datetime.now()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_auto_20181107_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteedsafaris',
            name='book_before',
            field=models.DateField(default=datetime.now()),
        ),
        migrations.AlterField(
            model_name='guaranteedsafaris',
            name='depature_date',
            field=models.DateField(default=datetime.now()),
        ),
    ]
