# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_auto_20181107_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteedsafaris',
            name='book_before',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 23, 25, 5, 281203)),
        ),
        migrations.AlterField(
            model_name='guaranteedsafaris',
            name='depature_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 23, 25, 5, 281231)),
        ),
    ]
