# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0050_auto_20181107_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteedsafaris',
            name='book_before',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 23, 27, 27, 486461)),
        ),
        migrations.AlterField(
            model_name='guaranteedsafaris',
            name='depature_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 23, 27, 27, 486490)),
        ),
        migrations.AlterField(
            model_name='lowseason',
            name='package',
            field=models.OneToOneField( on_delete=django.db.models.deletion.CASCADE, to='profiles.Packages'),
        ),
    ]
