# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_auto_20181107_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowseason',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Packages'),
        ),
    ]
