# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0062_auto_20181108_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
