# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0064_auto_20181108_0054'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='guaranteedsafaris',
            name='Enter_Safari_Package',
            field=models.CharField(choices=[('ExNk', 'Excursions-lakenakuru'), ('ExNv', 'Excursions-lakenaivasha'), ('ExNai', 'Excursions-nairobiexcursions'), ('2dyab', '2 days - aberdare'), ('2dyam', '2 days - amboseli'), ('2dynk', '2 days - nakuru'), ('2dynv', '2 days - naivasha'), ('2dysw', '2 days - sweetwaters'), ('3dyam', '3 days - amboseli'), ('3dyma', '3 days - maasaimara '), ('3dynk', '3 days - nakuru'), ('3dysa', '3 days - samburu'), ('3dysw', '3 days - sweetwaters'), ('4dymank', '4 days - maranakuru'), ('5dyam', '5 days - amboseli')], default='title', max_length=20),
        ),
    ]
