# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0066_auto_20181108_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuaranteedSafaris',
        ),
    ]
