# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0067_delete_guaranteedsafaris'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedSafaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Safari_Package', models.CharField(choices=[('ExNk', 'Excursions-lakenakuru'), ('ExNv', 'Excursions-lakenaivasha'), ('ExNai', 'Excursions-nairobiexcursions'), ('2dyab', '2 days - aberdare'), ('2dyam', '2 days - amboseli'), ('2dynk', '2 days - nakuru'), ('2dynv', '2 days - naivasha'), ('2dysw', '2 days - sweetwaters'), ('3dyam', '3 days - amboseli'), ('3dyma', '3 days - maasaimara '), ('3dynk', '3 days - nakuru'), ('3dysa', '3 days - samburu'), ('3dysw', '3 days - sweetwaters'), ('4dymank', '4 days - maranakuru'), ('5dyam', '5 days - amboseli')], max_length=20)),
                ('book_before', models.DateTimeField(default=datetime.datetime.now)),
                ('depature_date', models.DateTimeField(default=datetime.datetime.now)),
                ('Accomodation', models.CharField(choices=[('bg', 'Budget'), ('lx', 'Luxury')], default='accomodation', max_length=20)),
                ('people_booked', models.IntegerField(default=0)),
            ],
        ),
    ]
