# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0072_auto_20181108_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedsafaris',
            name='Enter_Safari_Package',
            field=models.CharField(choices=[('Excursions - Lake Nakuru', 'Excursions-lakenakuru'), ('Excursions - Lake Naivasha', 'Excursions-lakenaivasha'), ('Excursions - Nairobi Excursions', 'Excursions-nairobiexcursions'), ('2 DAYS ABERDARE NATIONAL PARK', '2 days - aberdare'), ('2 DAYS AMBOSELI SAFARI', '2 days - amboseli'), ('2 DAYS LAKE NAKURU NATIONAL PARK', '2 days - nakuru'), ('2 DAYS NAIVASHA SAFARI', '2 days - naivasha'), ('2 DAYS MAASAI MARA SAFARI', '2 DAYS MAASAI MARA SAFARI'), ('2 DAYS SWEETWATERS/ OL PEJETA CONSERVANCY SAFARI', '2 days - sweetwaters'), ('3 DAYS AMBOSELI SAFARI', '3 days - amboseli'), ('3 DAYS MAASAI MARA SAFARI', '3 days - maasaimara '), ('3 DAYS LAKE NAKURU NATIONAL PARK', '3 days - nakuru'), ('3 DAYS SAMBURU SAFARI', '3 days - samburu'), ('3 DAYS SWEETWATERS/ OL PEJETA CONSERVANCY SAFARI', '3 days - sweetwaters'), ('4 DAYS MAASAI MARA/NAKURU SAFARI', '4 days - maranakuru'), ('5 DAYS AMBOSELI - NAKURU - MARA SAFARI', '5 days - amboseli')], max_length=40),
        ),
    ]
