# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0077_auto_20181108_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedsafaris',
            name='Season',
            field=models.CharField(choices=[('Low Season', 'Low Season'), ('High Season', 'High Season'), ('Peak Season', 'Peak Season')], default='season', max_length=20),
        ),
    ]
