# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0079_auto_20181108_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinGroup',
        ),
        migrations.AlterField(
            model_name='joinedsafaris',
            name='Hotel_Star',
            field=models.CharField(choices=[('2 star', '2 star'), ('3 star', '3 star'), ('4 star', '4 star'), ('Treetops ', 'Treetops Aberdare'), ('Ark ', 'Ark Aberdare')], default='hotelstar', max_length=20),
        ),
    ]
