# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0080_auto_20181109_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedsafaris',
            name='book_before',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='joinedsafaris',
            name='depature_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
