# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0084_auto_20181110_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinedsafaris',
            name='book_before',
        ),
        migrations.RemoveField(
            model_name='joinedsafaris',
            name='depature_date',
        ),
    ]
