# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 18:45
from __future__ import unicode_literals

from datetime import datetime; datetime.today
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0085_auto_20181110_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedsafaris',
            name='date_of_depature',
            field=models.DateField(default=datetime.today),
        ),
        migrations.AddField(
            model_name='joinedsafaris',
            name='today',
            field=models.DateField(default=datetime.today),
        ),
    ]
