# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0086_auto_20181110_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinedsafaris',
            name='date_of_depature',
        ),
        migrations.RemoveField(
            model_name='joinedsafaris',
            name='today',
        ),
        migrations.AddField(
            model_name='joinedsafaris',
            name='book_before',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='joinedsafaris',
            name='depature_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
