# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0087_auto_20181110_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedsafaris',
            name='book_day',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
