# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0088_joinedsafaris_book_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedsafaris',
            name='book_day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
