# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0090_auto_20181112_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinedsafaris',
            name='book_day',
        ),
    ]
