# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0093_auto_20181112_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedsafaris',
            name='today_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
