# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0094_joinedsafaris_today_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedsafaris',
            name='Accomodation',
            field=models.CharField(choices=[('Budget', 'Budget'), ('Luxury', 'Luxury')], default='accomodation', max_length=20),
        ),
        migrations.AlterField(
            model_name='joinedsafaris',
            name='people_booked',
            field=models.IntegerField(default=0, max_length=7),
        ),
    ]
