# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0096_excursionprices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedsafaris',
            name='people_booked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='joinedsafaris',
            name='today_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
